### ISSUE TITLE
STM32WB55   SysEx Message

### ISSUE THREAD

**Issue by Gabsepuez** [Hypnotriod/midi-box-stm32#10]
Hello from Austria!

thank you for your work in this project, it helps me a lot!

I encounter a problem when i want to make a custom SysEx message about MIDI(or the midi protocol).

So when i send a normal Message, like Note ON or similar, everything works fine.
But when i want to send the command 0xF0 for SysEx, the USB doesnt go to IDLE Mode.

I found out, that the DataInStage will be not called.
So when i call the USBD_MIDI_DataInHandler hard coded, then it starts at least the transaction.

Here the part of the code 

![image](https://github.com/Hypnotriod/midi-box-stm32/assets/98836310/e183e6af-da00-4bcd-aed9-5cc2ba4d07d3)

Do you know why,or what could i try? 

regards

**Comment by Gabsepuez** [comment]
i downloaded the MidiViewer for Windows and there it seems that my program doesn't send a Midi SysEx Message.

**Comment by Hypnotriod** [comment]
Hi. Can you try to send full 64 bytes usb report with one message?

**Comment by Gabsepuez** [comment]
I tried different things now

1.
![image](https://github.com/Hypnotriod/midi-box-stm32/assets/98836310/e8bca692-2c27-4ce5-b66c-8f1164867759)
There i get something from the midi to the pc

Declaration of it:
![image](https://github.com/Hypnotriod/midi-box-stm32/assets/98836310/767747b6-0b2d-414f-aac0-5a7aabb602cc)


2.
![image](https://github.com/Hypnotriod/midi-box-stm32/assets/98836310/559c7406-10bd-4dcb-ae0c-5b4f2b81e923)
There i get nothing.


Is there a special charakter for the SysEx message(without the beginning one) that must be part of it, that the midi interface recognize it? 


Edit:
I also recognized, that the midi won't send, until i send one Note On Message before. I looked up in that code, but make nothing different. I send there 4x8Bit. When i did this, i see also the data that comes from the a_cLogs(The logs, and not the start or end message from SysEx). Do i have to send there something else before?

**Comment by Gabsepuez** [comment]
When i set the first byte to 0x0F, i receive a message.

Is there any programm, where i can record/see all the midi/usb data?

**Comment by Hypnotriod** [comment]
I'm not familiar with System Exclusive messages, but as I understood - it should start with 0xF0 and end with 0xF7  
Try to find some example of proper message and send it?  
Maybe this monitoring software will do the trick (I haven't used it personally): [MIDIMonitor](https://www.snoize.com/MIDIMonitor/)  
Try to debug...

**Comment by Gabsepuez** [comment]
Okay, after couple of hours debugging, i found out that according to the manual i have to send 0x04 first and then 0xF0 second and in the end 0xF7 
There are couple of differences how many bytes you can send.

![image](https://github.com/Hypnotriod/midi-box-stm32/assets/98836310/65867499-aa5c-498f-ba05-fc534d7c0237)
So in my case, i send everytime 64Byte. I do a 0x04 and a 0xF0, then data and in the end the 0xF7.

Works perfectly for me now.

For everyone looking for a program to control the data
RTMidi with sourcecode
MidiView as normal application.

Thanks for your effort
