### ISSUE TITLE
Endpoint inconsistency

### ISSUE THREAD

**Issue by x-moe-x** [Hypnotriod/midi-box-stm32#11]
Hi,

thanks for the great work!

I found an inconsistency regarding endpoint configuration: In the descriptor the EPs are configured as BULK, in USBD_MIDI_Init however they are opened as Type Interrupt.

Kind regards,

Moe

**Comment by Hypnotriod** [comment]
I see. This could be the reason of that [Double Buffering](https://github.com/Hypnotriod/midi-box-stm32/issues/9) issue...
Could you please confirm that replacing `USBD_EP_TYPE_INTR` with `USBD_EP_TYPE_BULK` in `USBD_MIDI_Init` -> `USBD_LL_OpenEP` calls does not brake anything?

**Comment by Hypnotriod** [comment]
I'll try to test it over the weekend and commit the fix.

**Comment by Hypnotriod** [comment]
Anyway. Have checked it on the device and seems no issues so far. Did the [commit](https://github.com/Hypnotriod/midi-box-stm32/commit/231c11da816e36df618e5c224df6ebc4f2f5ddc7)
