### ISSUE TITLE
patch instructions for stm32H733 missing HAL_PCDEx_PMAConfig line

### ISSUE THREAD

**Issue by TrevorCash** [Hypnotriod/midi-box-stm32#12]
Hi,

I am following your patch instructions.  I am on stm32cubeide 1.13.2

there is no line similar to:

`HAL_PCDEx_PMAConfig((PCD_HandleTypeDef*)pdev->pData , 0x81 , PCD_SNG_BUF, 0x100); // leave this line as is`

In USB_DEVICE/Target/usbd_conf.c

Perhaps this has moved to something different?

Project File:
[project.zip](https://github.com/user-attachments/files/17348226/project.zip)

**Comment by Hypnotriod** [comment]
As I can see there is no such method in `stm32h7xx_hal_pcd_ex.c`.  
So I assume that at least the `stm32h7 HAL driver` does not support the `PMA` (Packet Memory Area) feature.  
So as it says above in the section - "no action required" :)

**Comment by Hypnotriod** [comment]
Anyway, I can not find anything about the Packet Memory Area for the `stm32h` family in its [Reference Manual](https://www.st.com/resource/en/reference_manual/rm0468-stm32h723733-stm32h725735-and-stm32h730-value-line-advanced-armbased-32bit-mcus-stmicroelectronics.pdf)
So just ignore that section...
