### ISSUE TITLE
Can you compile your project in STM32CubeIDE 1.10.1?

### ISSUE THREAD

**Issue by P55-rgb** [Hypnotriod/midi-box-stm32#2]

**Comment by Hypnotriod** [comment]
Done. You can now check this branch: **cube-ide**

**Comment by Hypnotriod** [comment]
Are you from russia? If so, then you should fuck off!

**Comment by P55-rgb** [comment]
Ha, ha, ha...
Do not forget to close all Russian culture: ballet, Pushkin, Tchaikovsky, Bulgakov, Stalin, Putin, etc.
Welcome to the Russian world )))
