### ISSUE TITLE
Nucleo 103 shows up as File node

### ISSUE THREAD

**Issue by UlliSouth** [Hypnotriod/midi-box-stm32#6]
Hi, first of all thanks for the readme. Everything went almost fine. I had redefinitions of the UART interrupt callback functions. Not a real problem. 

But: after flashing the board shows always up as mass storage device instead of a midi device. 

What I am doing wrong here? Can you please give me a hint?

Thanks,
Ulli

**Comment by Hypnotriod** [comment]
Could you tell me how you connect the Nucleo 103 to a PC if there is no USB port installed on board?

**Comment by UlliSouth** [comment]
Hi, you are absolutely right. I fixed the connection. Thanks!
